/* Al-Quran Pro service worker v2: offline app shell, preloaded images, offline audio */
const SHELL='qa-shell-v2',RT='qa-rt-v1',ASSET_CACHE='qa-assets-v1',AUDIO_CACHE='qa-audio-v1';
const ASSETS=["https://i.ibb.co/fGZcq4Qv/38be1f71d8b5.png", "https://i.ibb.co/MkwBQk45/e1989d8290d1.png", "https://i.ibb.co/BKyj3YR1/6fd2df8572a2.jpg", "https://i.ibb.co/Z0PWXK5/9f7f6ca263da.png", "https://i.ibb.co/vxmZR64s/66c66654d13f.png", "https://i.ibb.co/d0zrftSB/c3c6eaac473b.jpg", "https://i.ibb.co/2YjFd8Yg/2377d3594ad1.jpg", "https://i.ibb.co/nNHTdmDc/0818ac1fe2cf.png", "https://i.ibb.co/4ZJBWRdr/84ad37cb8cec.jpg", "https://i.ibb.co/Qv0FTSmk/36631a537d27.jpg", "https://i.ibb.co/vvYpFTxd/fb7802493631.jpg", "https://i.ibb.co/LXwk5TxL/456fc426ceeb.jpg", "https://i.ibb.co/jZ9THmnz/6cd9f35da194.jpg", "https://i.ibb.co/Z1KksM1j/7ce99594ae75.jpg", "https://i.ibb.co/MxgfCg1D/49dd81e4a8d8.jpg", "https://i.ibb.co/WvqJhhtq/065ccbfa7b05.jpg", "https://i.ibb.co/rGH6wsGP/96b8499ad779.jpg", "https://i.ibb.co/QvzcYQG2/1736b64f6ab4.png"];
const CORE=['./','./index.html','./manifest.json','./icon-192.png','./icon-512.png','./names.mp3'];
self.addEventListener('install',e=>{e.waitUntil((async()=>{const c=await caches.open(SHELL);await Promise.allSettled(CORE.map(u=>c.add(u)));
 const ac=await caches.open(ASSET_CACHE);await Promise.allSettled(ASSETS.map(async u=>{if(await ac.match(u))return;try{const r=await fetch(u,{mode:'cors'});if(r.ok)return ac.put(u,r);throw 0}catch(x){try{await ac.put(u,await fetch(u,{mode:'no-cors'}))}catch(y){}}}));
 self.skipWaiting()})())});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith('qa-shell-')&&k!==SHELL).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
function rangeFrom(resp,req){const h=req.headers.get('range');if(!h)return resp;return resp.blob().then(b=>{const m=/bytes=(\d*)-(\d*)/.exec(h);const s=+m[1]||0;let e=m[2]?+m[2]:b.size-1;e=Math.min(e,b.size-1);return new Response(b.slice(s,e+1),{status:206,statusText:'Partial Content',headers:{'Content-Type':resp.headers.get('Content-Type')||'audio/mpeg','Content-Range':`bytes ${s}-${e}/${b.size}`,'Content-Length':e-s+1}})})}
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);
 if(r.mode==='navigate'){e.respondWith(fetch(r).then(x=>{const cp=x.clone();caches.open(SHELL).then(c=>c.put('./index.html',cp));return x}).catch(()=>caches.match('./index.html')));return}
 if(u.origin===location.origin){if(u.pathname.startsWith('/api/'))return;e.respondWith(caches.open(SHELL).then(async c=>{const hit=await c.match(r,{ignoreSearch:true});const net=fetch(r).then(x=>{if(x.ok&&x.status===200&&!r.headers.get('range'))c.put(r,x.clone());return x}).catch(()=>null);if(hit){net.catch(()=>{});return rangeFrom(hit,r)}const x=await net;return x||new Response('',{status:504})}));return}
 if(/(^|\.)ibb\.co$/.test(u.host)){e.respondWith(caches.open(ASSET_CACHE).then(async c=>{const hit=await c.match(r.url);if(hit)return hit;try{const x=await fetch(r);if(x.ok||x.type==='opaque')c.put(r.url,x.clone());return x}catch(err){return Response.error()}}));return}
 if((r.destination==='audio'||r.destination==='video')){e.respondWith((async()=>{const c=await caches.open(AUDIO_CACHE);const hit=await c.match(r.url);if(hit)return hit.type==='opaque'?hit:rangeFrom(hit,r);return fetch(r)})());return}
 if(/fonts\.(googleapis|gstatic)\.com$/.test(u.host)||u.host==='upload.wikimedia.org'||(u.host==='cdn.jsdelivr.net'&&u.pathname.includes('hls'))){e.respondWith(caches.open(RT).then(async c=>{const hit=await c.match(r);if(hit)return hit;try{const x=await fetch(r);if(x.ok||x.type==='opaque')c.put(r,x.clone());return x}catch(err){return hit||Response.error()}}))}
});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(self.clients.matchAll({type:'window'}).then(cs=>cs.length?cs[0].focus():self.clients.openWindow('./')))});
